version: '3'
services:
  postgresql:
    image: postgres
    container_name: nestProject
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=nestProject
      - POSTGRES_PASSWORD=02623120
      - POSTGRES_DATABASE=nestProject
    command: postgres
    restart: always


  redis:
    image: redis:alpine3.14
    container_name: redis-nestProject
    ports:
      - "6379:6379"